# X stands for stop codon
codon_to_res = {
    'TCA': 'S',
    'TCC': 'S',
    'TCG': 'S',
    'TCT': 'S',
    'TTC': 'F',
    'TTT': 'F',
    'TTA': 'L',
    'TTG': 'L',
    'TAC': 'Y',
    'TAT': 'Y',
    'TAA': 'X',
    'TAG': 'X',
    'TGC': 'C',
    'TGT': 'C',
    'TGA': 'X',
    'TGG': 'W',
    'CTA': 'L',
    'CTC': 'L',
    'CTG': 'L',
    'CTT': 'L',
    'CCA': 'P',
    'CCC': 'P',
    'CCG': 'P',
    'CCT': 'P',
    'CAC': 'H',
    'CAT': 'H',
    'CAA': 'Q',
    'CAG': 'Q',
    'CGA': 'R',
    'CGC': 'R',
    'CGG': 'R',
    'CGT': 'R',
    'ATA': 'I',
    'ATC': 'I',
    'ATT': 'I',
    'ATG': 'M',
    'ACA': 'T',
    'ACC': 'T',
    'ACG': 'T',
    'ACT': 'T',
    'AAC': 'N',
    'AAT': 'N',
    'AAA': 'K',
    'AAG': 'K',
    'AGC': 'S',
    'AGT': 'S',
    'AGA': 'R',
    'AGG': 'R',
    'GTA': 'V',
    'GTC': 'V',
    'GTG': 'V',
    'GTT': 'V',
    'GCA': 'A',
    'GCC': 'A',
    'GCG': 'A',
    'GCT': 'A',
    'GAC': 'D',
    'GAT': 'D',
    'GAA': 'E',
    'GAG': 'E',
    'GGA': 'G',
    'GGC': 'G',
    'GGG': 'G',
    'GGT': 'G',
    'UNK': 'X'
}

# most frequent codon for each residue
res_to_codon = {'M': 'ATG', 'T': 'ACC', 'P': 'CCG', 'K': 'AAA', 'F': 'TTT', 'L': 'CTG', 'I': 'ATC', 'V': 'GTG',
                'C': 'TGC', 'S': 'AGC', 'A': 'GCC', 'R': 'CGC', 'N': 'AAT', 'D': 'GAT', 'G': 'GGC', 'Q': 'CAG',
                'Y': 'TAT', 'W': 'TGG', 'E': 'GAA', 'H': 'CAC', 'X': 'UNK'}

codon_types = list(codon_to_res.keys())
codon_order = {codon: i for i, codon in enumerate(codon_types)}
unk_codon = 'UNK'
unk_codon_index = codon_order[unk_codon]
